foodapp/urls.py
from django.conf.urls.defaults import url, patterns, include

from views import HomepageView, OrderListView, UserOrderView, TodaysOrdersView

urlpatterns = (
    url(r'^$', HomepageView.as_view(), name='url_homepage'),
    url(r'^orders/$', OrderListView.as_view(), name='url_orders'),
    url(r'^orders/user/(?P<username>\w+)/$', UserOrderView.as_view(), name='url_user_orders'),
    url(r'^orders/today/$', TodaysOrdersView.as_view(), name='url_todays_orders'),
    #url(r'^orders/items/(?P<pk>\d+)/$', view, name='url_item_orders'),
)

project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^project/', include('project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('foodapp.urls', namespace='foodapp')),

    url(r'accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'accounts/login.html'}, name='url_login_view'),
)

foodapp/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    once_a_day = models.BooleanField()

    def __unicode__(self):
        return '%s: %s' % (self.name, self.description,)

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'


class Order(models.Model):
    user = models.ForeignKey(User)
    date = models.DateField(default=datetime.date.today)
    item = models.ForeignKey(Item)
    quantity = models.PositiveSmallIntegerField(default=1)

    def __unicode__(self):
        return '%d %s(s) on %s.' % (self.quantity, self.item.name, self.date,)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'
        ordering = ['date']

foodapp/forms.py
from django.forms import ModelForm

from foodapp.models import Order

class OrderForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Order
        exclude = ["user", "date"]

foodapp/views.py
import datetime

from django.http import HttpResponseRedirect
from django.views.generic import CreateView, ListView
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from foodapp.forms import OrderForm
from foodapp.models import Item, Order


class HomepageView(CreateView):
    form_class = OrderForm
    success_url = reverse_lazy('foodapp:url_todays_orders')
    template_name = 'foodapp/homepage.html'
    object = Order

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(HomepageView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            item_pk = request.POST.get('item', None)

            if item_pk is not None:
                item = Item.objects.get(pk=item_pk)
            else:
                raise AttributeError('Could not locate item with pk %s' % item_pk)

            if item and item.once_a_day:
                order = None

                try:
                    order = Order.objects.filter(user=request.user).get(item__pk=item_pk, date=datetime.date.today)
                    return self.render_to_response(self.get_context_data(form=form, error='This item has already been ordered'))
                except Order.DoesNotExist:
                    obj.user = request.user
                    obj.save()
                    return HttpResponseRedirect(self.success_url)
            else:
                obj.user = request.user
                obj.save()
                return HttpResponseRedirect(self.success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class OrderListView(ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'foodapp/orders.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(OrderListView, self).dispatch(*args, **kwargs)


class UserOrderView(OrderListView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserOrderView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        username = self.kwargs.get('username', None)

        if username is not None:
            return Order.objects.filter(user__username=username)

    def get_context_data(self, **kwargs):
        context = super(UserOrderView, self).get_context_data(**kwargs)
        context['title'] = 'Order History for ' + self.request.user.username
        return context


class TodaysOrdersView(OrderListView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TodaysOrdersView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(TodaysOrdersView, self).get_context_data(**kwargs)
        orders = Order.objects.filter(date=datetime.date.today)
        context['orders'] = orders

        # The following piece of code is a hackish way to find the # of cups of rice needed
        burrito_count = 0
        for order in orders:
            if order.item.name.strip().lower().find('burrito') > -1:
                burrito_count = burrito_count + order.quantity
        context['rice_quantity'] = burrito_count * 0.5

        context['title'] = 'Today\'s Orders'
        return context

foodapp/templates/foodapp/base.html
<!doctype html>
<html lang="en">
<head>
    <title>Food Ordering</title>

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}vendor/bootstrap/css/bootstrap.min.css" />

    <!-- Custom -->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" />

    {% block extracss %}{% endblock extracss %}

    {% block extrajs %}{% endblock extrajs %}
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="navbar">
                    <div class="navbar-inner">
                        <a class="brand" href="{% url 'foodapp:url_homepage' %}">foodapp</a>
                        <ul class="nav">
                            <li><a href="{% url 'foodapp:url_homepage' %}">Place Order</a></li>
                            <li><a href="{% url 'foodapp:url_user_orders' username=user %}">My Order History</a></li>
                            <li><a href="{% url 'foodapp:url_todays_orders' %}">Today's Orders</a></li>
                        </ul>
                        <ul class="nav pull-right">
                            {% if user.is_authenticated %}
                                <li><a href="#">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'url_login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        {% block content %}{% endblock content %}
    </div>
</body>
</html>

foodapp/templates/foodapp/homepage.html
{% extends "foodapp/base.html" %}

{% load bootstrap_toolkit %}

{% block content %}
    <div class="row">
        <div class="span8">
            <h2>Place your order</h2>
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                {{ form|as_bootstrap:"horizontal" }}
                <div class="control-group">
                    <div class="controls">
                        <button type="submit" class="btn btn-primary">Place Order</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

foodapp/templates/foodapp/orders.html
{% extends 'foodapp/base.html' %}

{% block content %}
    <div class="row">
        <div class="span12">
            {% if title %}
                <h2>{{ title }}</h2>
            {% else %}
                <h2>Order History</h2>
            {% endif %}

            {% if counts %}
                {% for key, value in counts %}
                    <p><h3>{{ key }}:</h3> {{ value }}</p>
                {% endfor %}
            {% endif %}

            {% if error %}
                <h4 class="errorlist">{{ error }}</h4>
            {% endif %}

            {% if orders %}
                {% if rice_quantity %}
                    <h3>{{ rice_quantity }} cups of rice needed.</h3>
                {% endif %}

                {% for order in orders %}
                    <h4>{{ order }} <span style="font-size: .7em">by {{ order.user }}</span></h4>
                {% endfor %}
            {% else %}
                <h4>No orders today :(</h4>
            {% endif %}
        </div>
    </div>
{% endblock content %}